services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      FOUNDRY_PASSWORD: "${FOUNDRY_PASSWORD}"
      FOUNDRY_USERNAME: "${FOUNDRY_USERNAME}"
      CONTAINER_PRESERVE_CONFIG: "${CONTAINER_PRESERVE_CONFIG:-true}"
    ports:
      - "${FOUNDRY_PORT:-30000}:30000"  # Exposing Foundry on configurable port

  ddb-proxy:
    image: ghcr.io/mrprimate/ddb-proxy:latest
    restart: "unless-stopped"
    ports:
      - "${DDB_PROXY_PORT:-4000}:4000"  # DDB Proxy port mapping

networks:
  default:
    name: foundry_network
