projects:
  beyond-foundry:
    name: "Beyond Foundry Development"
    contexts:
      - name: "Core Module"
        paths:
          - "src/module/beyond-foundry.ts"
          - "src/module/api/BeyondFoundryAPI.ts"
          - "src/module/constants.ts"
          - "src/types/index.ts"
        priority: 1
        always_loaded: true
        tags: ["core", "api"]

      - name: "Module Utils"
        paths:
          - "src/module/utils/**/*.ts"
        priority: 2
        load_on_demand: true
        tags: ["utils", "settings", "logger"]

      - name: "Character Import Reference"
        paths:
          - "reference/ddb-importer/src/parser/character/**/*.js"
          - "reference/foundryvtt-dnd5e/system/data-models/actor/character.js"
        priority: 2
        load_on_demand: true
        tags: ["character", "parser", "reference"]

      - name: "Spell Import Reference"
        paths:
          - "reference/ddb-importer/src/parser/spells/**/*.js"
          - "reference/foundryvtt-dnd5e/system/data-models/item/spell.js"
        priority: 2
        load_on_demand: true
        tags: ["spells", "parser", "reference"]

      - name: "Authentication Reference"
        paths:
          - "reference/ddb-proxy/auth.js"
          - "reference/ddb-proxy/index.js"
          - "reference/ddb-importer/src/lib/DDBProxy.mjs"
        priority: 2
        load_on_demand: true
        tags: ["auth", "api", "reference"]

      - name: "Parsers Development"
        paths:
          - "src/parsers/**/*.ts"
        priority: 3
        load_on_demand: true
        tags: ["parsers", "development"]

    context_limits:
      max_files: 15
      max_size_mb: 6

    smart_loading:
      enabled: true
      strategy: "relevance"